/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication14;

/**
 *
 * @author Roan
 */
public class bon extends javax.swing.JFrame {

    /**
     * Creates new form bon
     */
    public bon() {
        initComponents();
        banyakdisable();
        jumlahdisable();
    }
    
    public void banyakdisable(){
        txt_usus_ndower.setEnabled(false);
        txt_ceker_ndower.setEnabled(false);
        txt_sayap_ndower.setEnabled(false);
        txt_kepala_ndower.setEnabled(false);
        txt_ayam_geprek.setEnabled(false);
        txt_mie_nelongso.setEnabled(false);
        txt_paket_nasi_ayam_geprek.setEnabled(false);
        txt_paket_mie_ayam_geprek.setEnabled(false);
        txt_nasi.setEnabled(false);
        txt_mie_goreng.setEnabled(false);
        txt_telor_ceplok.setEnabled(false);
        air_mineral.setEnabled(false);
        txt_teh_pucuk.setEnabled(false);
    }
    
    public void jumlahdisable(){
        txt_usus_ndower1.setEnabled(false);
        txt_ceker_ndower1.setEnabled(false);
        txt_sayap_ndower1.setEnabled(false);
        txt_kepala_ndower1.setEnabled(false);
        txt_ayam_geprek1.setEnabled(false);
        txt_mie_nelongso1.setEnabled(false);
        txt_paket_nasi_ayam_geprek1.setEnabled(false);
        txt_paket_mie_ayam_geprek1.setEnabled(false);
        txt_nasi1.setEnabled(false);
        txt_mie_goreng1.setEnabled(false);
        txt_telor_ceplok1.setEnabled(false);
        air_mineral1.setEnabled(false);
        txt_teh_pucuk1.setEnabled(false);
    }
    
    public void jumlahvisibledisable(){
        txt_usus_ndower1.setVisible(false);
        txt_ceker_ndower1.setVisible(false);
        txt_sayap_ndower1.setVisible(false);
        txt_kepala_ndower1.setVisible(false);
        txt_ayam_geprek1.setVisible(false);
        txt_mie_nelongso1.setVisible(false);
        txt_paket_nasi_ayam_geprek1.setVisible(false);
        txt_paket_mie_ayam_geprek1.setVisible(false);
        txt_nasi1.setVisible(false);
        txt_mie_goreng1.setVisible(false);
        txt_telor_ceplok1.setVisible(false);
        air_mineral1.setVisible(false);
        txt_teh_pucuk1.setVisible(false);
        
    }
    
    public void jumlahvisibleenable(){
        txt_usus_ndower1.setVisible(true);
        txt_ceker_ndower1.setVisible(true);
        txt_sayap_ndower1.setVisible(true);
        txt_kepala_ndower1.setVisible(true);
        txt_ayam_geprek1.setVisible(true);
        txt_mie_nelongso1.setVisible(true);
        txt_paket_nasi_ayam_geprek1.setVisible(true);
        txt_paket_mie_ayam_geprek1.setVisible(true);
        txt_nasi1.setVisible(true);
        txt_mie_goreng1.setVisible(true);
        txt_telor_ceplok1.setVisible(true);
        air_mineral1.setVisible(true);
        txt_teh_pucuk1.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb_air_mineral = new javax.swing.JCheckBox();
        txt_mie_goreng1 = new javax.swing.JTextField();
        cb_teh_pucuk = new javax.swing.JCheckBox();
        txt_telor_ceplok1 = new javax.swing.JTextField();
        txt_usus_ndower = new javax.swing.JTextField();
        txt_ceker_ndower = new javax.swing.JTextField();
        air_mineral1 = new javax.swing.JTextField();
        txt_teh_pucuk1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_sayap_ndower = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_kepala_ndower = new javax.swing.JTextField();
        txt_ayam_geprek = new javax.swing.JTextField();
        txt_mie_nelongso = new javax.swing.JTextField();
        txt_paket_nasi_ayam_geprek = new javax.swing.JTextField();
        txt_paket_mie_ayam_geprek = new javax.swing.JTextField();
        txt_nasi = new javax.swing.JTextField();
        txt_mie_goreng = new javax.swing.JTextField();
        txt_telor_ceplok = new javax.swing.JTextField();
        air_mineral = new javax.swing.JTextField();
        txt_teh_pucuk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cb_ceker_ndower = new javax.swing.JCheckBox();
        cb_usus_ndower = new javax.swing.JCheckBox();
        cb_kepala_ndower = new javax.swing.JCheckBox();
        txt_usus_ndower1 = new javax.swing.JTextField();
        cb_sayap_ndower = new javax.swing.JCheckBox();
        cb_mie_nelongso = new javax.swing.JCheckBox();
        cb_ayam_geprek = new javax.swing.JCheckBox();
        cb_paket_nasi_ayam_geprek = new javax.swing.JCheckBox();
        txt_ceker_ndower1 = new javax.swing.JTextField();
        txt_sayap_ndower1 = new javax.swing.JTextField();
        txt_kepala_ndower1 = new javax.swing.JTextField();
        txt_ayam_geprek1 = new javax.swing.JTextField();
        cb_paket_mie_ayam_geprek = new javax.swing.JCheckBox();
        txt_mie_nelongso1 = new javax.swing.JTextField();
        cb_nasi = new javax.swing.JCheckBox();
        txt_paket_nasi_ayam_geprek1 = new javax.swing.JTextField();
        cb_mie_goreng = new javax.swing.JCheckBox();
        txt_paket_mie_ayam_geprek1 = new javax.swing.JTextField();
        cb_telor_ceplok = new javax.swing.JCheckBox();
        txt_nasi1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tujuan = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableprint2 = new javax.swing.JTable();
        txt_nim2 = new javax.swing.JLabel();
        txt_nama2 = new javax.swing.JLabel();
        txt_nama3 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_air_mineral.setText("Air Mineral");
        cb_air_mineral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_air_mineralActionPerformed(evt);
            }
        });

        txt_mie_goreng1.setText("0");

        cb_teh_pucuk.setText("Teh Pucuk");
        cb_teh_pucuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_teh_pucukActionPerformed(evt);
            }
        });

        txt_telor_ceplok1.setText("0");

        air_mineral1.setText("0");

        txt_teh_pucuk1.setText("0");

        jLabel16.setText("Jumlah");

        jLabel17.setText("Tujuan");
        jLabel17.setToolTipText("");

        txt_mie_nelongso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mie_nelongsoActionPerformed(evt);
            }
        });

        jLabel4.setText("Daftar Menu");

        jLabel5.setText("Banyak");

        Harga.setText("Harga");

        jLabel1.setText("Rp. 12.000");

        jLabel2.setText("Rp. 12.000");

        jLabel3.setText("Rp. 17.500");

        jLabel6.setText("Rp. 12.000");

        jLabel7.setText("Rp. 17.500");

        jLabel8.setText("Rp. 12.000");

        jLabel9.setText("Rp. 21.500");

        jLabel10.setText("Rp. 22.500");

        jLabel11.setText("Rp. 5.000");

        jLabel12.setText("Rp. 6.000");

        jLabel13.setText("Rp. 3.000");

        jLabel14.setText("Rp. 5.000");

        jLabel15.setText("Rp. 6.000");

        cb_ceker_ndower.setText("Ceker ndower");
        cb_ceker_ndower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ceker_ndowerActionPerformed(evt);
            }
        });

        cb_usus_ndower.setText("Usus ndower");
        cb_usus_ndower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_usus_ndowerActionPerformed(evt);
            }
        });

        cb_kepala_ndower.setText("Kepala Ndower");
        cb_kepala_ndower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kepala_ndowerActionPerformed(evt);
            }
        });

        txt_usus_ndower1.setText("0");
        txt_usus_ndower1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_usus_ndower1KeyReleased(evt);
            }
        });

        cb_sayap_ndower.setText("Sayap ndower");
        cb_sayap_ndower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sayap_ndowerActionPerformed(evt);
            }
        });

        cb_mie_nelongso.setText("Mie nelongso");
        cb_mie_nelongso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mie_nelongsoActionPerformed(evt);
            }
        });

        cb_ayam_geprek.setText("Ayam Geprek");
        cb_ayam_geprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ayam_geprekActionPerformed(evt);
            }
        });

        cb_paket_nasi_ayam_geprek.setText("Paket nasi ayam geprek");
        cb_paket_nasi_ayam_geprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_paket_nasi_ayam_geprekActionPerformed(evt);
            }
        });

        txt_ceker_ndower1.setText("0");

        txt_sayap_ndower1.setText("0");

        txt_kepala_ndower1.setText("0");

        txt_ayam_geprek1.setText("0");

        cb_paket_mie_ayam_geprek.setText("Paket mie ayam geprek");
        cb_paket_mie_ayam_geprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_paket_mie_ayam_geprekActionPerformed(evt);
            }
        });

        txt_mie_nelongso1.setText("0");

        cb_nasi.setText("Nasi");
        cb_nasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_nasiActionPerformed(evt);
            }
        });

        txt_paket_nasi_ayam_geprek1.setText("0");

        cb_mie_goreng.setText("Mie Goreng");
        cb_mie_goreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mie_gorengActionPerformed(evt);
            }
        });

        txt_paket_mie_ayam_geprek1.setText("0");

        cb_telor_ceplok.setText("Telor Ceplok/Dadar");
        cb_telor_ceplok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_telor_ceplokActionPerformed(evt);
            }
        });

        txt_nasi1.setText("0");

        Tujuan.setColumns(20);
        Tujuan.setRows(5);
        jScrollPane1.setViewportView(Tujuan);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cetak Preview");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_ceker_ndower)
                                .addComponent(cb_sayap_ndower)
                                .addComponent(cb_kepala_ndower)
                                .addComponent(cb_ayam_geprek)
                                .addComponent(cb_mie_nelongso)
                                .addComponent(cb_paket_nasi_ayam_geprek)
                                .addComponent(cb_usus_ndower))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_nasi)
                                .addComponent(cb_paket_mie_ayam_geprek)
                                .addComponent(cb_mie_goreng)
                                .addComponent(cb_telor_ceplok)
                                .addComponent(cb_air_mineral)
                                .addComponent(cb_teh_pucuk))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Harga))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5))
                            .addComponent(txt_paket_mie_ayam_geprek, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(txt_ayam_geprek)
                            .addComponent(txt_kepala_ndower)
                            .addComponent(txt_sayap_ndower)
                            .addComponent(txt_ceker_ndower)
                            .addComponent(txt_usus_ndower)
                            .addComponent(txt_mie_nelongso)
                            .addComponent(txt_paket_nasi_ayam_geprek)
                            .addComponent(txt_nasi)
                            .addComponent(txt_mie_goreng)
                            .addComponent(txt_telor_ceplok)
                            .addComponent(air_mineral)
                            .addComponent(txt_teh_pucuk))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_teh_pucuk1)
                            .addComponent(air_mineral1)
                            .addComponent(txt_telor_ceplok1)
                            .addComponent(txt_mie_goreng1)
                            .addComponent(txt_nasi1)
                            .addComponent(txt_paket_mie_ayam_geprek1)
                            .addComponent(txt_paket_nasi_ayam_geprek1)
                            .addComponent(txt_mie_nelongso1)
                            .addComponent(txt_ayam_geprek1)
                            .addComponent(txt_kepala_ndower1)
                            .addComponent(txt_sayap_ndower1)
                            .addComponent(txt_ceker_ndower1)
                            .addComponent(txt_usus_ndower1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel16))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_usus_ndower1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ceker_ndower1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_sayap_ndower1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kepala_ndower1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ayam_geprek1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mie_nelongso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_paket_nasi_ayam_geprek1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_paket_mie_ayam_geprek1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mie_goreng1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telor_ceplok1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(air_mineral1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_teh_pucuk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(Harga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_usus_ndower)
                            .addComponent(txt_usus_ndower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_ceker_ndower)
                            .addComponent(txt_ceker_ndower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_sayap_ndower)
                            .addComponent(txt_sayap_ndower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_kepala_ndower)
                            .addComponent(txt_kepala_ndower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_ayam_geprek)
                            .addComponent(txt_ayam_geprek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_mie_nelongso)
                            .addComponent(txt_mie_nelongso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_paket_nasi_ayam_geprek)
                            .addComponent(txt_paket_nasi_ayam_geprek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_paket_mie_ayam_geprek)
                            .addComponent(txt_paket_mie_ayam_geprek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_nasi)
                            .addComponent(txt_nasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_mie_goreng)
                            .addComponent(txt_mie_goreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_telor_ceplok)
                            .addComponent(txt_telor_ceplok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_air_mineral)
                            .addComponent(air_mineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_teh_pucuk)
                            .addComponent(txt_teh_pucuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        jLabel24.setText("Toko Kafe Mamat");

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel25.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel25.setText("No nota         :");

        jLabel26.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel26.setText("Tanggal         :");

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        tableprint2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableprint2.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(tableprint2);

        txt_nim2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        txt_nim2.setText("N");

        txt_nama2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        txt_nama2.setText("N");

        txt_nama3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        txt_nama3.setText("N");

        jLabel27.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jLabel27.setText("Tujuan          :");

        jLabel28.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        jLabel28.setText("Jumlah : Rp.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nim2)
                                    .addComponent(txt_nama2)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_nama3))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(92, 92, 92))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txt_nim2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_nama2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_nama3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_telor_ceplokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_telor_ceplokActionPerformed
        // TODO add your handling code here:
        if(cb_telor_ceplok.isSelected()){
            txt_telor_ceplok.setEnabled(true);
        } else {
            txt_telor_ceplok.setEnabled(false);
        }
    }//GEN-LAST:event_cb_telor_ceplokActionPerformed

    private void cb_mie_gorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mie_gorengActionPerformed
        // TODO add your handling code here:
        if(cb_mie_goreng.isSelected()){
            txt_mie_goreng.setEnabled(true);
        } else {
            txt_mie_goreng.setEnabled(false);
        }
    }//GEN-LAST:event_cb_mie_gorengActionPerformed

    private void cb_nasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_nasiActionPerformed
        // TODO add your handling code here:
        if(cb_nasi.isSelected()){
            txt_nasi.setEnabled(true);
        } else {
            txt_nasi.setEnabled(false);
        }
    }//GEN-LAST:event_cb_nasiActionPerformed

    private void cb_paket_mie_ayam_geprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_paket_mie_ayam_geprekActionPerformed
        // TODO add your handling code here:
        if(cb_paket_mie_ayam_geprek.isSelected()){
            txt_paket_mie_ayam_geprek.setEnabled(true);
        } else {
            txt_paket_mie_ayam_geprek.setEnabled(false);
        }
    }//GEN-LAST:event_cb_paket_mie_ayam_geprekActionPerformed

    private void cb_paket_nasi_ayam_geprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_paket_nasi_ayam_geprekActionPerformed
        // TODO add your handling code here:
        if(cb_paket_nasi_ayam_geprek.isSelected()){
            txt_paket_nasi_ayam_geprek.setEnabled(true);
        } else {
            txt_paket_nasi_ayam_geprek.setEnabled(false);
        }
    }//GEN-LAST:event_cb_paket_nasi_ayam_geprekActionPerformed

    private void cb_ayam_geprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ayam_geprekActionPerformed
        // TODO add your handling code here:
        if(cb_ayam_geprek.isSelected()){
            txt_ayam_geprek.setEnabled(true);
        } else {
            txt_ayam_geprek.setEnabled(false);
        }
    }//GEN-LAST:event_cb_ayam_geprekActionPerformed

    private void cb_mie_nelongsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mie_nelongsoActionPerformed
        // TODO add your handling code here:
        if(cb_mie_nelongso.isSelected()){
            txt_mie_nelongso.setEnabled(true);
        } else {
            txt_mie_nelongso.setEnabled(false);
        }
    }//GEN-LAST:event_cb_mie_nelongsoActionPerformed

    private void cb_sayap_ndowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sayap_ndowerActionPerformed
        // TODO add your handling code here:
        if(cb_sayap_ndower.isSelected()){
            txt_sayap_ndower.setEnabled(true);
        } else {
            txt_sayap_ndower.setEnabled(false);
        }
    }//GEN-LAST:event_cb_sayap_ndowerActionPerformed

    private void cb_kepala_ndowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kepala_ndowerActionPerformed
        // TODO add your handling code here:
        if(cb_kepala_ndower.isSelected()){
            txt_kepala_ndower.setEnabled(true);
        } else {
            txt_kepala_ndower.setEnabled(false);
        }
    }//GEN-LAST:event_cb_kepala_ndowerActionPerformed

    private void cb_usus_ndowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_usus_ndowerActionPerformed
        // TODO add your handling code here:
        if(cb_usus_ndower.isSelected()){
            txt_usus_ndower.setEnabled(true);
        } else {
            txt_usus_ndower.setEnabled(false);
        }
        
    }//GEN-LAST:event_cb_usus_ndowerActionPerformed

    private void cb_ceker_ndowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ceker_ndowerActionPerformed
        // TODO add your handling code here:
        if(cb_ceker_ndower.isSelected()){
            txt_ceker_ndower.setEnabled(true);
        } else {
            txt_ceker_ndower.setEnabled(false);
        }
    }//GEN-LAST:event_cb_ceker_ndowerActionPerformed

    private void cb_teh_pucukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_teh_pucukActionPerformed
        // TODO add your handling code here:
       if(cb_teh_pucuk.isSelected()){
            txt_teh_pucuk.setEnabled(true);
        } else {
            txt_teh_pucuk.setEnabled(false);
        }
    }//GEN-LAST:event_cb_teh_pucukActionPerformed

    private void cb_air_mineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_air_mineralActionPerformed
        // TODO add your handling code here:
        if(cb_air_mineral.isSelected()){
            air_mineral.setEnabled(true);
        } else {
            air_mineral.setEnabled(false);
        }
    }//GEN-LAST:event_cb_air_mineralActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int harga1 = 12000;
        int banyak1 = Integer.parseInt(txt_usus_ndower.getText());
        int jumlah1 = harga1 * banyak1;
        String jumlahS1 = String.valueOf(jumlah1);
        txt_usus_ndower1.setText(jumlahS1);
        
        int harga2 = 12000;
        int banyak2 = Integer.parseInt(txt_ceker_ndower.getText());
        int jumlah2 = harga2 * banyak2;
        String jumlahS2 = String.valueOf(jumlah2);
        txt_ceker_ndower1.setText(jumlahS2);
        
        int harga3 = 17500;
        int banyak3 = Integer.parseInt(txt_sayap_ndower.getText());
        int jumlah3 = harga3 * banyak3;
        String jumlahS3 = String.valueOf(jumlah3);
        txt_sayap_ndower1.setText(jumlahS3);

        int harga4 = 12000;
        int banyak4 = Integer.parseInt(txt_kepala_ndower.getText());
        int jumlah4 = harga4 * banyak4;
        String jumlahS4 = String.valueOf(jumlah4);
        txt_kepala_ndower1.setText(jumlahS4);

        int harga5 = 17500;
        int banyak5 = Integer.parseInt(txt_ayam_geprek.getText());
        int jumlah5 = harga5 * banyak5;
        String jumlahS5 = String.valueOf(jumlah5);
        txt_ayam_geprek1.setText(jumlahS5);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_mie_nelongsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mie_nelongsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mie_nelongsoActionPerformed

    private void txt_usus_ndower1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usus_ndower1KeyReleased

    }//GEN-LAST:event_txt_usus_ndower1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Harga;
    private javax.swing.JTextArea Tujuan;
    private javax.swing.JTextField air_mineral;
    private javax.swing.JTextField air_mineral1;
    private javax.swing.JCheckBox cb_air_mineral;
    private javax.swing.JCheckBox cb_ayam_geprek;
    private javax.swing.JCheckBox cb_ceker_ndower;
    private javax.swing.JCheckBox cb_kepala_ndower;
    private javax.swing.JCheckBox cb_mie_goreng;
    private javax.swing.JCheckBox cb_mie_nelongso;
    private javax.swing.JCheckBox cb_nasi;
    private javax.swing.JCheckBox cb_paket_mie_ayam_geprek;
    private javax.swing.JCheckBox cb_paket_nasi_ayam_geprek;
    private javax.swing.JCheckBox cb_sayap_ndower;
    private javax.swing.JCheckBox cb_teh_pucuk;
    private javax.swing.JCheckBox cb_telor_ceplok;
    private javax.swing.JCheckBox cb_usus_ndower;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable tableprint;
    private javax.swing.JTable tableprint1;
    private javax.swing.JTable tableprint2;
    private javax.swing.JTextField txt_ayam_geprek;
    private javax.swing.JTextField txt_ayam_geprek1;
    private javax.swing.JTextField txt_ceker_ndower;
    private javax.swing.JTextField txt_ceker_ndower1;
    private javax.swing.JTextField txt_kepala_ndower;
    private javax.swing.JTextField txt_kepala_ndower1;
    private javax.swing.JTextField txt_mie_goreng;
    private javax.swing.JTextField txt_mie_goreng1;
    private javax.swing.JTextField txt_mie_nelongso;
    private javax.swing.JTextField txt_mie_nelongso1;
    private javax.swing.JLabel txt_nama;
    private javax.swing.JLabel txt_nama1;
    private javax.swing.JLabel txt_nama2;
    private javax.swing.JLabel txt_nama3;
    private javax.swing.JTextField txt_nasi;
    private javax.swing.JTextField txt_nasi1;
    private javax.swing.JLabel txt_nim;
    private javax.swing.JLabel txt_nim1;
    private javax.swing.JLabel txt_nim2;
    private javax.swing.JTextField txt_paket_mie_ayam_geprek;
    private javax.swing.JTextField txt_paket_mie_ayam_geprek1;
    private javax.swing.JTextField txt_paket_nasi_ayam_geprek;
    private javax.swing.JTextField txt_paket_nasi_ayam_geprek1;
    private javax.swing.JTextField txt_sayap_ndower;
    private javax.swing.JTextField txt_sayap_ndower1;
    private javax.swing.JTextField txt_teh_pucuk;
    private javax.swing.JTextField txt_teh_pucuk1;
    private javax.swing.JTextField txt_telor_ceplok;
    private javax.swing.JTextField txt_telor_ceplok1;
    private javax.swing.JTextField txt_usus_ndower;
    private javax.swing.JTextField txt_usus_ndower1;
    // End of variables declaration//GEN-END:variables
}
